version: '3.8'

services:
    db:
        container_name: SUI
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=SUI
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app_network

    phpmyadmin:
        container_name: SUI_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=password
        depends_on:
            - db
        networks:
            - app_network

    loki:
        container_name: SUI_loki
        image: grafana/loki:latest
        ports:
            - '3100:3100'
        volumes:
            - ./backend/loki-config.yaml:/etc/loki/local-config.yaml
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - app_network

    grafana:
        container_name: SUI_grafana
        image: grafana/grafana:latest
        ports:
            - '3001:3000' # Grafana sur le port 3001 pour éviter un conflit avec l'API
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana-storage:/var/lib/grafana
        depends_on:
            - loki
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    minio_data:
    mysql_data:
    grafana-storage: 