export enum ApplicationParameterName {
    NEVER_CALLED_PROSPECTS_PERCENTAGE = 'NEVER_CALLED_PROSPECTS_PERCENTAGE',
    DEFAULT_PAGE_SIZE = 'DEFAULT_PAGE_SIZE',
    MAINTENANCE_MODE = 'MAINTENANCE_MODE',
    MAX_ALERTS_PER_USER = 'MAX_ALERTS_PER_USER',
    MAX_PROSPECTING_QUEUE_PROSPECTS = 'MAX_PROSPECTING_QUEUE_PROSPECTS',
    CALL_ABSENT_DELAY_HOURS = 'CALL_ABSENT_DELAY_HOURS',

    // Settings Autres - General Parameters
    DOWNPAYMENT_PROPORTION = 'DOWNPAYMENT_PROPORTION',
    AD_RENTALS_DAYS_CHECK = 'AD_RENTALS_DAYS_CHECK',

    // Settings Autres - Opportunity Management
    MIN_RELEVANT_OPPORTUNITY_PER_DOSSIER = 'MIN_RELEVANT_OPPORTUNITY_PER_DOSSIER',
    MIN_PREQUALIFIED_RENTAL_YIELD = 'MIN_PREQUALIFIED_RENTAL_YIELD',
    MAX_PREQUALIFIED_RENTAL_YIELD = 'MAX_PREQUALIFIED_RENTAL_YIELD',
    OPPORTUNITIES_EXPIRATION_DAYS = 'OPPORTUNITIES_EXPIRATION_DAYS',
    OPPORTUNITIES_HOURS_BEFORE_WAITING_TO_RESET = 'OPPORTUNITIES_HOURS_BEFORE_WAITING_TO_RESET',
    OPPORTUNITIES_CALLS_BEFORE_NOT_AVAILABLE = 'OPPORTUNITIES_CALLS_BEFORE_NOT_AVAILABLE',
    OPPORTUNITIES_REAL_ESTATE_YIELD = 'OPPORTUNITIES_REAL_ESTATE_YIELD',
    SEARCH_CRITERIA_MIN_AMOUNT_OPPORTUNITIES_FOR_MAX_RENTAL_YIELD = 'SEARCH_CRITERIA_MIN_AMOUNT_OPPORTUNITIES_FOR_MAX_RENTAL_YIELD',

    // Settings Autres - Power Dialer
    MIN_POWER_DIALER_SESSION_STOCK_SIZE = 'MIN_POWER_DIALER_SESSION_STOCK_SIZE',
    MAX_POWER_DIALER_SESSION_BATCH_SIZE = 'MAX_POWER_DIALER_SESSION_BATCH_SIZE',

    // Settings Autres - Automatic Notifications
    EMAIL_OFFER = 'EMAIL_OFFER',
    SMS_OFFER = 'SMS_OFFER',
    EMAIL_AGENT_SIGNED = 'EMAIL_AGENT_SIGNED',
    SMS_AGENT_SIGNED = 'SMS_AGENT_SIGNED',
    SMS_QUALIFIED = 'SMS_QUALIFIED',
    SMS_EXPIRED = 'SMS_EXPIRED',

    // Settings Autres - Autopilot
    AUTOPILOT_ACTIVE = 'AUTOPILOT_ACTIVE',
    DOSSIER_AUTOPILOT_FREQUENCY_DAYS = 'DOSSIER_AUTOPILOT_FREQUENCY_DAYS',
    MAX_AUTOPILOT_PER_DAY = 'MAX_AUTOPILOT_PER_DAY',
    OWNER_AVAILABILITY_HOURS = 'OWNER_AVAILABILITY_HOURS',

    // Settings Sourcing - Opportunity Cleaning
    OPPORTUNITIES_PER_DOSSIER = 'OPPORTUNITIES_PER_DOSSIER',
    MIN_QUALIFIED_YIELD = 'MIN_QUALIFIED_YIELD',
    OPPORTUNITY_EXPIRATION_DAYS = 'OPPORTUNITY_EXPIRATION_DAYS',
    RELAUNCH_DURATION_HOURS = 'RELAUNCH_DURATION_HOURS',
    CALLS_BEFORE_UNAVAILABLE = 'CALLS_BEFORE_UNAVAILABLE',

    // Settings Sourcing - Power Dialer Strategy
    GLOBAL_CALL_STRATEGY = 'GLOBAL_CALL_STRATEGY',
    POWER_DIALER_SLOTS = 'POWER_DIALER_SLOTS',

    // Settings Sourcing - Yield Sorting Parameters
    DESCENDING_YIELD_SORT_ENABLED = 'DESCENDING_YIELD_SORT_ENABLED',
    MIN_TARGETED_YIELD = 'MIN_TARGETED_YIELD',
    MAX_TARGETED_YIELD = 'MAX_TARGETED_YIELD',

    // Settings Sourcing - Power Dialer Thresholds
    MIN_OPPORTUNITY_THRESHOLD = 'MIN_OPPORTUNITY_THRESHOLD',
    MEDIUM_OPPORTUNITY_THRESHOLD = 'MEDIUM_OPPORTUNITY_THRESHOLD',
    MAX_OPPORTUNITY_THRESHOLD = 'MAX_OPPORTUNITY_THRESHOLD',

    // Settings SDR - Consultant Management
    CONSULTANT_GROUPS = 'CONSULTANT_GROUPS',
    MAX_MEETINGS_PER_CONSULTANT = 'MAX_MEETINGS_PER_CONSULTANT',

    // Settings SDR - Form R1 Parameters
    FORM_MIN_DOWN_PAYMENT = 'FORM_MIN_DOWN_PAYMENT',
    FORM_MEDIUM_DOWN_PAYMENT = 'FORM_MEDIUM_DOWN_PAYMENT',
    FORM_MAX_DOWN_PAYMENT = 'FORM_MAX_DOWN_PAYMENT',
    FORM_MIN_SAVING = 'FORM_MIN_SAVING',
    FORM_MEDIUM_SAVING = 'FORM_MEDIUM_SAVING',
    ANNUAL_INCOME_THRESHOLD = 'ANNUAL_INCOME_THRESHOLD',

    // Settings SDR - SDR Parameters
    SDR_PARAMETER_BONUS = 'SDR_PARAMETER_BONUS',
    NB_CALL_WITHOUT_ANSWER = 'NB_CALL_WITHOUT_ANSWER',
    CALL_REPARTITION = 'CALL_REPARTITION',
    MAX_MEETINGS_PER_WEEK = 'MAX_MEETINGS_PER_WEEK',
}